version: '3.9'
name: qllm

services:
  qllm-fastapi:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://qllm:qllm@postgres:5432/qllm
    volumes:
      - .:/app

  postgres:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_DB: qllm
      POSTGRES_USER: qllm
      POSTGRES_PASSWORD: qllm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local
