"""Sync data schema

Revision ID: 11a619e24bd5
Revises: 0a26dbae5dec
Create Date: 2024-12-11 15:18:25.945606

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11a619e24bd5"
down_revision: Union[str, None] = "0a26dbae5dec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
