"""Sync database schema

Revision ID: 6c74c3d3939b
Revises: c3308de4a9cd
Create Date: 2024-12-11 10:14:41.894868

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6c74c3d3939b"
down_revision: Union[str, None] = "c3308de4a9cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chat_conversations_id", table_name="chat_conversations")
    op.drop_table("chat_conversations")
    op.drop_index("ix_medical_records_id", table_name="medical_records")
    op.drop_table("medical_records")
    op.drop_index("ix_chat_histories_id", table_name="chat_histories")
    op.drop_table("chat_histories")
    op.drop_index("ix_users_id", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "password_hash", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("age", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("gender", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
        sa.UniqueConstraint("email", name="users_email_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_users_id", "users", ["id"], unique=False)
    op.create_table(
        "chat_histories",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="chat_histories_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="chat_histories_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_chat_histories_id", "chat_histories", ["id"], unique=False)
    op.create_table(
        "medical_records",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "file_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("file_path", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="medical_records_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="medical_records_pkey"),
    )
    op.create_index("ix_medical_records_id", "medical_records", ["id"], unique=False)
    op.create_table(
        "chat_conversations",
        sa.Column("chat_history_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "messages",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chat_history_id"],
            ["chat_histories.id"],
            name="chat_conversations_chat_history_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="chat_conversations_pkey"),
    )
    op.create_index(
        "ix_chat_conversations_id", "chat_conversations", ["id"], unique=False
    )
    # ### end Alembic commands ###
