"""Sync database schema

Revision ID: aebe87a697e1
Revises: 6c74c3d3939b
Create Date: 2024-12-11 10:19:44.344083

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aebe87a697e1"
down_revision: Union[str, None] = "6c74c3d3939b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
