"""fix relationship user - medicalrecord

Revision ID: bdd45921ae97
Revises: 88d6781c0e25
Create Date: 2025-02-14 17:17:23.090332

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bdd45921ae97"
down_revision: Union[str, None] = "88d6781c0e25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_memory_id"), "memory", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_memory_id"), table_name="memory")
    # ### end Alembic commands ###
