"""fix relationship user - memory

Revision ID: f0eb2333c81c
Revises: bdd45921ae97
Create Date: 2025-02-14 17:18:34.305349

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0eb2333c81c"
down_revision: Union[str, None] = "bdd45921ae97"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
